# Generated by Django 4.2.13 on 2024-07-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0002_surveyquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer',
        ),
    ]
