# Generated by Django 4.2.13 on 2024-08-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0003_remove_surveyquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
