# Generated by Django 4.2.13 on 2024-08-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0004_alter_surveyquestion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splash.surveyquestion')),
            ],
        ),
    ]
