# Generated by Django 4.2.13 on 2024-08-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0005_surveyanswers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyAnswers',
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
    ]
